builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: binary

brews:
  - tap:
      owner: dbirks
      name: get-jwt
    description: A helper utility to make it easier to get a JWT
    homepage: https://github.com/dbirks/get-jwt
    license: Apache2
